// src/app/shared/constants/referencias.const.ts
export const REFERENCIAS_A = [
  "AMIGO LO CONOCE HACE 5 AÑOS LO REFIERE COMO ESTRATEGICA",
  "AMIGO LO CONOCE HACE 10 AÑOS LO REFIERE COMO RESPONSABLE",
  "AMIGO LO CONOCE HACE 3 AÑOS LO REFIERE COMO HONESTA",
  "AMIGO LO CONOCE HACE 9 AÑOS LO REFIERE COMO CARISMATICO",
  "AMIGO LO CONOCE HACE 2 AÑOS LO REFIERE COMO PERSEVERANTE",
  "AMIGO LO CONOCE HACE 3 AÑOS LO REFIERE COMO PERSONA COHERENTE",
  "AMIGO LO CONOCE HACE 7 AÑOS LO REFIERE COMO PERSONA AGRADECIDA",
  "AMIGO LO CONOCE HACE 1 AÑO LO REFIERE COMO PERSONA TOLERANTE",
  "AMIGO LO CONOCE HACE 13 AÑOS LO REFIERE COMO PERSONA EFICAZ",
  "AMIGO LO CONOCE HACE 4 AÑOS LO REFIERE COMO PERSONA OBJETIVA",
  "AMIGO LO CONOCE HACE 15 AÑOS LO REFIERE COMO PERSONA SENCILLA",
  "AMIGO LO CONOCE HACE 6 AÑOS LO REFIERE COMO PERSONA ESPONTANEA",
  "AMIGO LO CONOCE HACE 5 AÑOS LO REFIERE COMO PERSONA ANALITICA",
  "AMIGO LO CONOCE HACE 16 AÑOS LO REFIERE COMO PERSONA REALISTA",
  "AMIGO LO CONOCE HACE 8 AÑOS LO REFIERE COMO PERSONA LUCHADORA",
  "AMIGO LO CONOCE HACE 11 AÑOS LO REFIERE COMO PERSONA DINAMICA",
  "AMIGO LO CONOCE HACE 4 AÑOS LO REFIERE COMO PERSONA TRANQUILA",
  "AMIGO LO CONOCE HACE 7 AÑOS LO REFIERE COMO PERSONA SOLIDARIA",
  "AMIGO LO CONOCE HACE 12 AÑOS LO REFIERE COMO PERSONA OBJETIVA",
  "AMIGO LO CONOCE HACE 18 AÑOS LO REFIERE COMO PERSONA EXIGENTE",
  "AMIGO LO CONOCE HACE 15 AÑOS LO REFIERE COMO PERSONA PERSEVERANTE",
  "AMIGO LO CONOCE HACE 7 AÑOS LO REFIERE COMO PERSONA COLABORADORA"
] as const;

export const REFERENCIAS_F = [
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA HONESTA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA AMBICIOSA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA PUNTUAL",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA PUNTUAL",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA CARISMATICA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA TOLERANTE",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA PACIENTE",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA ACERTADA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA OPTIMISTA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA AGIL",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA EXPERTA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA ORIENTADA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA PERSISTENTE",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA COLABORADOR",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA TRABAJADOR",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA TRABAJADOR",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA SOBRESALIENTE",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA SOBRESALIENTE",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA INTEGRA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA INTEGRA",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA AGRADABLE",
  "LO CONOCE DE TODA LA VIDA LO REFIERE COMO PERSONA BONDADOSA"
] as const;

// (Opcional) tipo derivado por índice para autocompletado estricto
export type ReferenciaA = typeof REFERENCIAS_A[number];
export type ReferenciaF = typeof REFERENCIAS_F[number];
